language: node_js
node_js:
  - "6"
after_success:
  - npm install codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=be90486b1b028ef539b8d9057a84d840ced7df810231ba0c9f43a225dc6633fe codeclimate-test-reporter < coverage/lcov.info
